language: r
sudo: required
warnings_are_errors: false

before_install:
  - sudo apt-get update

r_binary_packages:

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
